/* ============================================================
 * M2 五大景区讲解库 · 预置双语数据
 * landmarks：大纲列明景点逐个介绍（双语）
 * structure：讲解结构拆解（中文常显）
 * ============================================================ */
XH.spots = [
/* ==================== ① 外滩 ==================== */
{
  id:'bund', score:10,
  name:{ zh:'外滩景区', en:'The Bund' },
  profile:{
    status:{ zh:'上海城市名片 · 万国建筑博览群', en:'The city’s calling card · an exhibition of international architecture' },
    highlight:{ zh:'百年历史与当代天际线“古今同框”', en:'A century of history framed beside a modern skyline' }
  },
  landmarks:[
    { name:{zh:'黄浦江',en:'the Huangpu River'}, desc:{zh:'各位请看身边的黄浦江，上海的母亲河。它全长约113公里，平均宽400米、深9米，发源于淀山湖，在吴淞口汇入长江，所以古代也叫“春申江”“黄歇浦”。黄浦江把上海分成浦东、浦西，也是上海的航运大动脉，港深水阔、四季通航。江的一边是陆家嘴的未来高楼，一边是外滩的历史建筑。想细细欣赏，可以坐游船，分日游和夜游；夜晚灯光亮起，两岸最为迷人。黄浦江的名字，还和一位历史名人有关：战国时期楚国的春申君黄歇曾治理这一带水道，上海别称“申城”便由此而来。江边有多处游船码头，航程约五十分钟，船行江上，可以从最好的角度欣赏两岸；晚上还有灯光秀，是上海夜游的必选项目。',
      en:'Ladies and gentlemen, please look at the Huangpu River beside us — the mother river of Shanghai. It is about 113 kilometers long, 400 meters wide and 9 meters deep on average. It starts from Dianshan Lake and joins the Yangtze River at the Wusong Mouth, so in old times it was also called the Chunshen River. The river divides Shanghai into Pudong and Puxi. It is also the city’s shipping artery, with deep water and an all-season harbor. On one side rise the futuristic towers of Lujiazui; on the other stand the historic buildings of the Bund. To enjoy the views, you can take a day or night cruise. When night falls and the lights come on, the river is at its most beautiful. The river’s name is linked to a historical figure: Huang Xie, Lord Chunshen of the Warring States period, once managed the waterways here, which is why Shanghai is also called “Shen”. There are several cruise piers along the bank. A trip takes about 50 minutes and gives you the finest view of both shores, and in the evening there is a bright light show — a must for a night tour of Shanghai.'} },
    { name:{zh:'外白渡桥',en:'the Waibaidu Bridge (Garden Bridge)'}, desc:{zh:'各位请看这座钢铁大桥——外白渡桥。“外白渡”就是“免费渡河”的意思：建桥前，人们坐摆渡过苏州河要付船费；1907年大桥通车后，步行过桥分文不收，名字就此叫开。它是中国第一座钢桥，连接黄浦区与虹口区，脚下正是苏州河汇入黄浦江的地方。2008年还有一段佳话：老桥整体被小心切割，运到工厂彻底翻新，一年后原样搬回原处，就像给老爷爷换了一副强壮的新骨架。它是一本活着的上海历史书，把老上海和新上海连在一起。其实在它之前，这里1856年就有过一座木桥，过桥要收铜钱，普通百姓受尽刁难；1873年旁边另建了一座免费木桥，大家叫它“外白渡桥”，1907年才换成今天的钢桥。所以这座桥也见证了上海从屈辱走向自信。',
      en:'Please look at this steel bridge — the Waibaidu Bridge. Its name means “the free ferry”. Before the bridge, people had to pay to take a ferry across Suzhou Creek. When the bridge opened in 1907, everyone could cross on foot for free, and the name stayed. It was the first steel bridge in China. It joins Huangpu District and Hongkou District, right where Suzhou Creek flows into the Huangpu River. There is also a warm story from 2008. The old bridge was carefully cut into pieces, moved to a factory for a full renewal, and brought back to the same place one year later — like giving an old grandfather a strong new body. It is a living history book of Shanghai, connecting old Shanghai with the new city. In fact, an earlier wooden bridge stood here in 1856, but people had to pay to cross and ordinary visitors were treated unfairly. In 1873 a free wooden bridge was built beside it and called Waibaidu, before today’s steel bridge replaced it in 1907. So this bridge has watched Shanghai grow from humiliation to confidence.'} },
    { name:{zh:'黄浦公园',en:'Huangpu Park'}, desc:{zh:'桥旁这片绿地是黄浦公园，始建于1868年，是中国第一座对公众开放的公园，历史上还叫过“公共花园”“外滩公园”。园内最醒目的是人民英雄纪念塔，纪念为上海献出生命的英雄；塔旁还有巨型石雕，再现上海历史上的重要事件。向西望是外白渡桥，隔江相望是东方明珠、上海中心等浦东高楼，身后又是外滩成排的老建筑。因为这个独特的视角，这里成了外滩最受欢迎的拍照点之一，也是新老上海交汇的地方。请大家记住这段历史：公园刚建成时只准外国人进入，旧时园规曾让中国人深感屈辱；新中国成立后，公园才真正属于人民。园内还建有外滩历史纪念馆，用老照片讲述外滩百年变迁。清晨的公园里，市民跳舞、打拳、唱沪剧，是感受本地生活的好地方。',
      en:'The green area beside the bridge is Huangpu Park, first opened in 1868 as the first public park in China. In history it was also called the Public Garden or the Bund Park. The most eye-catching sight inside is the Memorial Tower to the People’s Heroes, which honors the heroes of Shanghai’s history. Next to it stands a huge stone carving showing the important events of the city’s past. To the west you can see the Waibaidu Bridge. Across the river rise the Oriental Pearl Tower, Shanghai Tower and other Pudong skyscrapers, while behind us stand the grand old buildings of the Bund. With this special view, the park is one of the most popular photo spots on the Bund, a place where old and new Shanghai meet. Please remember its history: when the park first opened, only foreigners were allowed in, and the old rules deeply hurt the Chinese people; after 1949 the park truly belonged to the people. It also holds the Bund History Museum, where old photos tell the Bund’s hundred-year story. In the early morning, local people dance, do tai chi and sing Shanghai opera here — a wonderful place to feel real city life.'} },
    { name:{zh:'上海总会大楼旧址',en:'the Old Shanghai Club (Waldorf Astoria)'}, desc:{zh:'这幢气派的大楼是上海总会大楼旧址，1910年建成，曾是在沪英国绅士的社交俱乐部。它最出名的是楼内一条约34米长的吧台，当年号称“远东最长吧台”，能同时坐满几十位客人。大楼是典型的新古典主义风格，高大的石柱、典雅的大堂，处处显示当时的奢华。2011年，这里经过精心修缮后成为外滩华尔道夫酒店，老楼的外墙、楼梯和长吧台都按原样保留，还加入了现代酒店的舒适。走进一楼长廊，仿佛还能听见一百年前绅士们谈笑声。大楼由英国建筑师设计，六根高大的爱奥尼克石柱撑起门面，是外滩新古典主义的代表作。上世纪七八十年代它改名东风饭店；1989年，上海第一家肯德基就开在这栋楼里，当年尝鲜的队伍排到了街角。百年大楼里既有绅士的吧台，也留下了普通上海人的时髦记忆。',
      en:'This grand building is the old Shanghai Club, completed in 1910. It was once a social club for British gentlemen in Shanghai. Its most famous feature was a bar counter about 34 meters long, known as the longest bar in the Far East, with seats for dozens of guests. The building is in a fine neoclassical style, with tall stone columns and an elegant hall that show the luxury of those times. After careful renewal, it became the Waldorf Astoria Shanghai on the Bund in 2011. Its historic outer wall, stairs and the famous Long Bar were kept as they were, together with all the comfort of a modern hotel. Walking into its long hall, you can almost hear the talk and laughter of the gentlemen from a hundred years ago. Designed by British architects, its facade is held up by six tall Ionic columns, a fine neoclassical work of the Bund. In the 1970s and 80s it was called the Dongfeng Hotel, and in 1989 the very first KFC in Shanghai opened in this building, with queues running to the street corner. So this century-old building holds both the gentlemen’s Long Bar and the fashion memories of ordinary Shanghai people.'} },
    { name:{zh:'汇丰银行大楼旧址',en:'the Old HSBC Building'}, desc:{zh:'带穹顶的这幢大楼是汇丰银行大楼旧址，1923年建成，当年被称为“苏伊士运河以东最讲究的建筑”，今天是浦发银行大楼。它有著名的“三宝”：第一宝是门口一对铜狮，张嘴的叫“施迪”、闭嘴的叫“史蒂芬”，老上海相信摸一摸铜狮会带来好运；第二宝是穹顶上33幅马赛克镶嵌画，描绘日月星辰和人间世界；第三宝是大堂28根意大利大理石柱，每根直径1米、高6米，其中4根由整块天然大理石雕成，据说同样的整石柱全世界只有6根，另外两根在巴黎卢浮宫。再讲一个铜狮的故事：两只狮子各有名字，张口吼叫的叫“施迪”，安静闭嘴的叫“史蒂芬”，都取自当年汇丰两位大班的名字。抗战时铜狮曾被日军掠走，万幸战后归来；如今门前的是复制品，真品被妥善收藏在上海市历史博物馆里，我们在人民广场就能看到。',
      en:'The domed building is the old HSBC Building, completed in 1923. It was once praised as “the finest building east of Suez”, and today it is the Pudong Development Bank Building. It is famous for three treasures. The first is a pair of bronze lions at the gate. Old Shanghai people believed that touching the lions brought good luck. The second treasure is the dome ceiling: 33 mosaic pictures showing the sun, the stars and the human world. The third is a set of 28 Italian marble pillars in the lobby, each one meter wide and six meters tall. Four of them were cut from single natural blocks. It is said that there are only six such pillars in the world, and the other two are in the Louvre in Paris. Here is the story of the bronze lions: they have their own names — the roaring one is Stitt and the quiet one is Stephen, named after two HSBC managers. The Japanese army took them away during the war, but luckily they returned after 1945. The lions at the door today are copies; the real ones are carefully kept in the Shanghai History Museum, which we will visit at People’s Square.'} },
    { name:{zh:'江海关大楼旧址',en:'the Old Customs House'}, desc:{zh:'旁边这座带高耸钟楼的大楼是江海关大楼旧址，1927年建成，在很长时间里都是上海最高的建筑之一。楼顶大钟曾是亚洲最大的钟，上海人亲切地叫它“大清钟”，钟声低沉洪亮，传得很远。它最特别的是报时：每隔15分钟奏响一段《东方红》，到了整点就演奏全曲。对几代上海人来说，这钟声就是城市的声音。请大家看大楼底部，入口高大、列柱粗壮，显得格外稳重——当年江海关掌管进出上海的船只与货物，是一座城市经贸地位的象征。江海关的历史可以追溯到1685年清康熙年间，是中国最早的海关之一。眼前这座大钟由英国钟表厂按伦敦大本钟的风格铸造，钟面直径近6米，每周上链一次。八十多年来，钟声伴着外滩潮起潮落，提醒人们珍惜时间，也记录着上海外贸的百年风云。',
      en:'Next to it stands the tall clock-tower building, the old Customs House, completed in 1927. For a long time it was one of the tallest buildings in Shanghai. Its big clock was once the largest in Asia, and local people call it the Big Ching. Its sound is deep, loud and carries very far. Its most special feature is the chime: every 15 minutes it plays a part of the famous Chinese song “The East is Red”, and on the hour it plays the whole song. For several generations in Shanghai, this sound has been the voice of the city. Please look at the bottom of the building. The entrance is huge, with thick tall columns that make it look strong and trustworthy. In old times the Customs controlled all the ships and goods entering Shanghai, a symbol of the city’s power in trade. The customs office here dates back to 1685 in the Qing Dynasty, making it one of the earliest customs houses in China. The great clock was made by a British clockmaker in the style of London’s Big Ben, with a face nearly six meters wide and wound once a week. For over 80 years its chimes have followed the tides of the Bund, reminding people to value time and recording a century of Shanghai’s foreign trade.'} },
    { name:{zh:'沙逊大厦旧址',en:'Sassoon House'}, desc:{zh:'请看这幢顶着绿色金字塔顶的大楼——沙逊大厦，1929年建成，高77米，曾是外滩第一高楼。楼顶金字塔用深绿色铜皮覆盖，高19米，远远看去就像埃及金字塔。这里当年是华懋饭店，设有英、中、印、日等九个国家风格的套房，客人就像在一天内环游世界。它还有一段“高度之争”：隔壁中国银行想建得更高，可主人沙逊爵士势力很大，不许邻居超过自己，中行大楼只好削矮一截，所以直到今天绿色塔顶仍略胜一筹。1956年这里改为和平饭店，老年爵士乐队每晚演奏，接待过世界各地的名人。整幢楼是典型的装饰艺术风格，当年设有270间客房，每一间都豪华考究。这支老年爵士乐队1980年成立，乐手多是白发苍苍的老人，几十年来每晚演出不辍，连外国元首也专门来听。爵士乐配上老上海，和平饭店的夜晚因此格外迷人。',
      en:'Please look at the building with the green pyramid roof — Sassoon House, completed in 1929. At 77 meters, it was once the tallest building on the Bund. The 19-meter pyramid roof is covered with dark green copper and looks just like an Egyptian pyramid from far away. It was once the Cathay Hotel, with suites in nine different country styles, such as British, Chinese, Indian and Japanese. Staying there felt like traveling around the world in one day. There is also a height story. The Bank of China next door wanted to build higher, but the powerful owner, Mr. Victor Sassoon, would not let any neighbor stand taller, so the bank had to make its building shorter. Even today the green roof stays a little higher. Since 1956 it has been the Peace Hotel, where the Old Jazz Band plays every night for guests from all over the world. The building is a classic Art Deco work and once had 270 guest rooms, each richly decorated. The Old Jazz Band was formed in 1980, and its white-haired musicians have played every night for decades; even foreign leaders come to listen. Jazz music and old Shanghai together make the evening here truly special.'} },
    { name:{zh:'中国银行大楼旧址',en:'the Old Bank of China Building'}, desc:{zh:'与和平饭店相邻的是中国银行大楼旧址，1937年建成。它在外滩非常特别：周边大楼几乎都由外国建筑师设计，只有这一幢出自中国建筑师之手，因此成为中国人的骄傲。请看楼顶，蓝色琉璃瓦屋檐是典型的中国传统风格，与现代楼体结合得恰到好处。楼内同样令人印象深刻：地下曾设有远东最大的金库，有成千上万个保管箱；墙面和门窗上还有许多中式雕刻。它不只是石头和钢铁，更象征着当年中国人的自信——中国人同样能建造一流的现代银行大楼。大楼共17层，由中国建筑师陆谦受主持设计；1937年建成时恰逢抗战爆发，原本更高的方案被迫缩减。中国银行的前身是1912年成立的中国银行，是中国历史最悠久的银行之一。从被迫削矮的屋檐到今日的国家金融脊梁，这栋楼浓缩了中国银行家的骨气。',
      en:'Next to the Peace Hotel stands the old Bank of China Building, completed in 1937. It is very special on the Bund. Almost all the other buildings here were designed by foreign architects, and this was the only one designed by Chinese architects, so it became a source of national pride. Please look at its roof: the eaves of blue glazed tiles are in the traditional Chinese style, perfectly mixed with a modern building. The inside is also impressive. Underground it once had the largest treasury in the Far East, with thousands of safe deposit boxes, and the walls and doors carry many fine Chinese carvings. It is not just stone and steel. It is a symbol of Chinese confidence — showing that Chinese people could also build a first-class modern bank. The building has 17 floors and was led by Chinese architect Luke Him Sau. It was finished in 1937, just as the war broke out, so an even taller plan had to be cut short. Its owner, the Bank of China, was founded in 1912 and is one of the oldest banks in the country. From a roof forced lower to today’s financial strength, this building holds the pride of Chinese bankers.'} },
    { name:{zh:'外滩源',en:'Bund Origin (Waitanyuan)'}, desc:{zh:'我们身后这片街区叫“外滩源”，顾名思义是外滩的起点。1843年上海开埠后，这里是最早的外国定居点之一：1849年英国领事馆设在此地，是上海现存最早的近代使领馆建筑之一。圆明园路两旁，老教堂、女青年会大楼、真光大楼等历史建筑保存完好。经过整修，今天的外滩源没有大拆大建，而是把老建筑变成美术馆、书店、咖啡馆和精品店，历史街区重新热闹起来。从外滩源走到江边，就像翻开一本从1843年写到今天的上海故事书。请大家抬头看，绿树丛中那座尖顶小教堂是新天安堂，建于1886年；圆明园路如今已改成步行街，老建筑里开着设计展和咖啡馆。这片区域“修旧如旧”，连石板路都保留了当年的纹理。这里也是拍婚纱和写真的热门地，站在路口向北望，外白渡桥的钢架正好入画。',
      en:'The area behind us is called Waitanyuan, which means the origin of the Bund. After Shanghai opened as a port in 1843, this was one of the earliest foreign settlements. The British Consulate was set up here in 1849, and its building is one of the oldest modern diplomatic buildings still standing in Shanghai. Along Yuanmingyuan Road, historic buildings are well kept — an old church, the YWCA building and many early office blocks. In the renewal, nothing was pulled down. Instead, the old buildings were turned into art galleries, bookstores, cafes and fine shops, and the historic quarter came alive again. Walking from Waitanyuan to the river is like opening a storybook of Shanghai, from 1843 all the way to today. Please look up: among the trees stands the small Union Church with its tall spire, built in 1886. Yuanmingyuan Road is now a pedestrian street, with design shows and cafes inside the old buildings. Everything here was repaired to look old, and even the stone pavements keep their original pattern. It is a favorite place for wedding photos, and looking north from the corner, the steel frame of the Waibaidu Bridge makes a perfect picture.'} }
  ],
  structure:[
    '<b>开场欢迎：</b>问候游客，点明外滩位置、长度与“万国建筑博览群”地位',
    '<b>空间定位：</b>身后历史建筑 + 右侧黄浦江 + 对岸陆家嘴，建立“一岸百年、一岸现代”的画面',
    '<b>建筑主体：</b>按游览动线逐一点名外白渡桥、上海总会、汇丰、海关、沙逊、中行大楼',
    '<b>亮点故事：</b>外白渡桥“免费渡河”得名与2008年整体大修、汇丰“三宝”、海关大钟奏《东方红》、沙逊与中行的“高度之争”',
    '<b>收尾引导：</b>“古今同框”点题，引导游客前往下一个景点'
  ],
  vocab:[
    {zh:'外滩',en:'the Bund'},{zh:'外白渡桥',en:'the Waibaidu Bridge (Garden Bridge)'},
    {zh:'黄浦公园',en:'Huangpu Park'},{zh:'上海总会',en:'the Shanghai Club'},
    {zh:'汇丰银行大楼',en:'the HSBC Building'},{zh:'江海关大楼',en:'the Customs House'},
    {zh:'沙逊大厦 / 和平饭店',en:'Sassoon House / the Peace Hotel'},
    {zh:'中国银行大楼',en:'the Bank of China Building'},{zh:'外滩源',en:'Waitanyuan / Bund Origin'},
    {zh:'万国建筑博览群',en:'an exhibition of international architecture'},
    {zh:'哥特式 / 巴洛克式 / 罗马式 / 新古典主义',en:'Gothic / Baroque / Romanesque / Neoclassical'}
  ],
  keywords:[
    {zh:'万国建筑博览群',en:'an exhibition of international architecture'},
    {zh:'古今同框',en:'the past and present in one frame'}
  ],
  body:[
    { v:3, zh:'各位游客，欢迎来到外滩。“外滩”的“滩”，在英语里是堤岸的意思；我们眼前这段长约1.5公里，北起外白渡桥，南至延安东路。19世纪40年代鸦片战争后，上海开埠，这里成为最早的外国居留地之一，领事馆、银行、饭店纷纷建起，到上世纪30年代建筑群基本成形。那时的外滩是财富的象征，被称为“远东的华尔街”。',
      en:'Ladies and gentlemen, welcome to the Bund. The word “bund” means an embankment, and this one runs about 1.5 kilometers, from the Waibaidu Bridge in the north to Yan’an Road in the south. After the Opium War in the 1840s, Shanghai opened as a treaty port, and this area became one of the earliest foreign settlements. Consulates, banks and hotels were built one after another, and the grand buildings we see took shape in the 1930s. At that time the Bund was a symbol of wealth, known as “the Wall Street of the Far East”.' },
    { v:3, zh:'外滩经历过两次大改造：上世纪90年代，防汛墙被加高，保护城市免受洪水；2010年世博会前又整修两年，耗资约50亿元，把车行道还给行人。建筑虽出自不同设计师、不同年代，但20多幢大楼沿江排开，风格和谐、气势非凡，被誉为“万国建筑博览群”；夜晚灯光亮起，更是迷人。',
      en:'The Bund has seen two great renewals. In the 1990s, the riverside wall was raised to protect the city from floods. Before the 2010 World Expo, it was rebuilt again for two years at a cost of about five billion yuan, turning roads into space for walkers. Although the buildings came from different designers and different times, more than 20 of them stand in one harmonious line, so the Bund is praised as “an exhibition of world architecture”. When night falls and the lights come on, it is truly charming.' },
    { v:3, zh:'我们面前的钢铁大桥是外白渡桥，1907年建成，是中国第一座钢桥，“外白渡”就是“免费渡河”的意思。2008年整桥拆卸大修，一年后原样归位。桥旁的黄浦公园建于1868年，是中国第一座公园。',
      en:'The steel bridge before us is the Waibaidu Bridge, built in 1907 as the first steel bridge in China. Its name means “the free ferry”. In 2008 it was taken apart for renewal and returned a year later. Beside it is Huangpu Park, opened in 1868 as the first public park in China.' },
    { v:3, zh:'沿江而行：1910年的上海总会大楼以34米“远东最长吧台”闻名，今天是华尔道夫酒店；带穹顶的是1923年汇丰银行大楼，曾被誉为“苏伊士运河以东最讲究的建筑”，镇楼“三宝”是铜狮、33幅马赛克天顶画和28根意大利大理石柱——其中4根整石雕刻，同样的石柱全球仅6根；旁边江海关大楼的大钟曾是亚洲第一，每15分钟奏响一段《东方红》。',
      en:'Walking along the river, the 1910 Shanghai Club was famous for its 34-meter “Long Bar” and is now the Waldorf Astoria. The domed HSBC Building of 1923 was once “the finest building east of Suez”, with three treasures: bronze lions, 33 mosaic ceiling paintings and 28 Italian marble pillars — four cut from single blocks, with only six such pillars worldwide. Next door, the Customs House clock was once the largest in Asia and still plays “The East is Red” every 15 minutes.' },
    { v:5, zh:'再往前，绿色金字塔顶是沙逊大厦，也就是和平饭店北楼：1929年高77米，曾是外滩第一高楼，19米高的铜皮金字塔像埃及金字塔，楼内有九国风格套房。旁边的中国银行大楼1937年建成，是外滩唯一由中国建筑师设计的大楼，蓝色琉璃瓦顶、曾设远东最大金库。当年中行想建得更高，沙逊爵士不允，所以今天绿顶仍略胜一筹。',
      en:'Further on, the green-pyramid Sassoon House, now the Peace Hotel North Building, was the Bund’s tallest in 1929 at 77 meters; its 19-meter copper roof looks Egyptian, and its suites were decorated in nine country styles. Next door, the 1937 Bank of China Building is the only Bund building by Chinese architects, with blue glazed tiles and once the Far East’s largest treasury. The bank wanted to build taller, but Mr. Sassoon refused — so the green roof still wins by a little today.' },
    { v:3, zh:'身后的街区叫“外滩源”，保留着1849年英国领事馆旧址。可以说，外滩的历史就是近代上海的缩影。江风正好，请大家随我漫步、拍照，也可选择晚上乘游船看两岸灯火。谢谢大家！',
      en:'The area behind us is Waitanyuan, the Bund’s origin, preserving the 1849 British Consulate. In many ways, the history of the Bund is the story of modern Shanghai in one place. The river wind is pleasant — please walk and take photos, or join a night cruise to see the lights on both banks. Thank you!' }
  ]
},
/* ==================== ② 人民广场 ==================== */
{
  id:'square', score:10,
  name:{ zh:'人民广场景区', en:'People’s Square' },
  profile:{
    status:{ zh:'上海的城市中心 · 政治文化地标群', en:'The heart of Shanghai · a cluster of political and cultural landmarks' },
    highlight:{ zh:'从跑马厅到人民广场，半部上海近代史', en:'From racecourse to people’s square — half of modern Shanghai’s history' }
  },
  landmarks:[
    { name:{zh:'中共一大纪念馆',en:'Memorial of the First CPC National Congress'}, desc:{zh:'各位游客，我们现在来到兴业路76号——中共一大纪念馆。这幢建筑是典型的上海石库门民居，建于1920年。1921年7月23日，中共一大在这里召开，会议通过了中国共产党的第一个纲领和第一个决议，选举产生了中央领导机构，宣告中国共产党诞生。1952年，这处会址被修缮保护，建立纪念馆并对公众开放；2021年，一座崭新的纪念馆落成，新展区面积超过3400平方米。馆内用图片、视频、雕塑和复原场景讲述这段历史，让人有身临其境之感。这里不仅是博物馆，更是重要的爱国主义教育基地。当时全国只有50多名党员，13位代表冒着生命危险从各地秘密赶来，其中就有年轻的毛泽东，共产国际也派代表参加。会议中途遭到密探注意，代表们紧急转移，最后一天在浙江嘉兴南湖的游船上开完，所以“红船精神”与这里紧紧相连。纪念馆免费开放，但需提前预约，馆内请保持安静。',
      en:'Ladies and gentlemen, we are now at No. 76 Xingye Road — the Memorial of the First CPC National Congress. The building is a typical Shanghai Shikumen house, built in 1920. On July 23, 1921, the First National Congress of the CPC was held here. At this meeting, the Party’s first creed and first resolution were passed, the central leading body was elected, and the birth of the Communist Party of China was announced. In 1952, the historic site was repaired and protected, and a memorial hall was opened to the public. In 2021, a beautiful new memorial building was completed, with a new exhibition area of over 3,400 square meters. Pictures, videos, sculptures and restored scenes tell the story inside, making visitors feel as if they were right there in 1921. This place is not just a museum, but also an important base for patriotic education. At that time the Party had only about 50 members. Thirteen delegates came secretly from all over China at the risk of their lives, among them the young Mao Zedong, together with representatives of the Communist International. A spy noticed the meeting, so the delegates moved away and held the final day on a boat on South Lake in Jiaxing, Zhejiang. That is why the “Red Boat spirit” is tied to this place. Admission is free with a booking, and please keep quiet inside.'} },
    { name:{zh:'上海博物馆',en:'Shanghai Museum'}, desc:{zh:'各位请看这座“天圆地方”的宏伟建筑——上海博物馆。它创建于1952年，1996年迁至人民广场现址，是一座以收藏、研究、展示中国古代艺术为主的大型博物馆。馆藏文物近102万件，其中定级的珍贵文物约14万件，青铜器、陶瓷器、书法、绘画的收藏都位居全国前列。建筑共七层，圆顶方座，体现中国“天圆地方”的传统宇宙观；南门两侧立有八尊中国传统神兽雕塑，北门正对着音乐喷泉和人民大厦。馆内青铜馆、绘画馆、书法馆等专题展厅各具特色，走进博物馆，就像登上一台穿越中华历史的时光机。馆内必看的是西周大克鼎，距今近三千年，鼎内290字铭文记载周天子的册命，由潘氏家族守护多年后捐给国家，是青铜馆的镇馆之宝。博物馆免费开放，可租借语音讲解；南门外八尊神兽各护一方，也是游客合影的热门位置。',
      en:'Please look at this grand building with a round top and a square base — the Shanghai Museum. It was founded in 1952 and moved to this site at People’s Square in 1996. It is a great museum focused on collecting, studying and showing ancient Chinese art. It holds nearly 1.02 million items, and about 140,000 of them are graded national treasures. Its collections of bronzes, ceramics, calligraphy and paintings are among the finest in China. The building has seven floors. Its round roof and square base show the traditional Chinese idea of “a round heaven and a square earth”. Eight sculptures of ancient sacred animals stand by the south entrance, while the north gate faces the music fountain and People’s Mansion. Inside, the bronze, painting and calligraphy galleries each have their own charm. Stepping into the museum is like stepping into a time machine through Chinese history. One must-see is the Da Ke Ding, a Western Zhou bronze tripod nearly 3,000 years old. Its 290-character inside inscription records the king’s appointment, and it was donated to the country after one family guarded it for years. The museum is free to enter, and audio guides are available. The eight sacred animals outside the south gate protect the eight directions and are popular for photos.'} },
    { name:{zh:'上海市历史博物馆（上海革命历史博物馆）',en:'Shanghai History Museum (Revolutionary History Museum)'}, desc:{zh:'这座带钟楼的漂亮老建筑，是上海市历史博物馆，馆舍本身就是1933年建成的原上海跑马总会大楼，钟楼至今是人民广场的标志之一。博物馆用1100多件文物，讲述上海从小镇到大都市的历史变迁。有三件宝贝别错过：第一对是曾立在外滩汇丰银行门口的铜狮；第二件是百子大礼轿，轿身上雕着一百个活泼可爱的孩子；第三件是民族英雄陈化成的铜炮——第一次鸦片战争中，他率兵英勇保卫上海，直至壮烈殉国。馆内还用现代科技复原老上海街景，走进去就像穿越回了一百年前。钟楼高53米，大钟每15分钟报时一次；跑马总会当年是西方人赛马、赌博的场所，普通中国人曾被拒之门外。2018年，历史博物馆在这里免费开放，东楼、西楼共展出1100多件文物，分“古代上海”和“近代上海”两部分。从跑马厅到人民的博物馆，建筑本身就是最生动的一件展品。',
      en:'This beautiful old clock-tower building is the Shanghai History Museum. The building itself is the former Shanghai Race Club, completed in 1933, and its clock tower is still a landmark of People’s Square. More than 1,100 artifacts inside tell the story of how Shanghai grew from a small town into a great modern city. Don’t miss three treasures. The first is a pair of bronze lions that once stood in front of the HSBC Building on the Bund. The second is the “hundred-children” wedding sedan, carved with one hundred lively children. The third is the bronze cannon of General Chen Huacheng, a national hero who led his soldiers to defend Shanghai in the First Opium War and gave his life for the city. Modern technology also brings old Shanghai streets back to life — walking in, you feel as if you had traveled back a hundred years. The clock tower is 53 meters tall and chimes every 15 minutes. The Race Club was once a place where Westerners raced horses and gambled while ordinary Chinese were kept outside. In 2018 the History Museum opened here for free, with over 1,100 artifacts in the east and west buildings, divided into ancient and modern Shanghai. From a racecourse to a museum of the people, the building itself is the most vivid exhibit of all.'} },
    { name:{zh:'上海城市规划展示馆',en:'Shanghai Urban Planning Exhibition Center'}, desc:{zh:'请大家看这座造型别致的建筑——上海城市规划展示馆，它的屋顶像四朵盛开的白玉兰，玉兰正是上海市花。这是一座讲述上海过去、现在和未来的特殊博物馆。一层“上海印象”，展示上海如何建设一座人民的城市；二层“人文之城”，能看到老城厢的街区模型，了解“15分钟社区生活圈”——在家门口就能满足日常生活所需；三层“创新之城”最精彩，5D数字沉浸式城市模型就像一个巨大的上海数字孪生；四层“生态之城”，展示上海如何变得更绿色、更可持续。一馆看尽城市的成长与梦想。老馆2000年开放，曾是人民广场最受欢迎的展馆之一；2021年闭馆重建，新馆融入了大量数字技术。屋顶的四朵白玉兰由钢架托起，夜晚亮灯时晶莹剔透。三楼的沉浸式沙盘最受欢迎：脚下和四周都是上海，从6000年前的古海岸讲到未来的智慧城市。完整参观约需两小时，免费但需提前预约。',
      en:'Please look at this special building — the Shanghai Urban Planning Exhibition Center. Its roof looks like four white magnolia flowers in bloom, and the magnolia is the city flower of Shanghai. This is a special museum about the city’s past, present and future. On the first floor, “Shanghai Impressions” shows how the city is built for its people. On the second floor, the “People City” presents a model of the old neighborhoods and explains the 15-minute community life circle, where all daily needs are close to home. The third floor, the “Innovation City”, is the most amazing: a 5D digital immersive city model, like a giant digital twin of Shanghai. On the fourth floor, the “Eco City” shows how Shanghai is becoming greener and more sustainable. In one building, you can see the growth and the dreams of the whole city. The old center opened in 2000 and was one of the most popular halls on the square; it was rebuilt after 2021 with a great deal of digital technology. Its four magnolias are held up by steel frames and shine like crystal at night. The immersive model on the third floor is the favorite: Shanghai appears all around and under your feet, from the ancient coastline 6,000 years ago to the future smart city. A full visit takes about two hours; admission is free with a booking.'} },
    { name:{zh:'国际饭店',en:'the Park Hotel'}, desc:{zh:'广场西侧这幢典雅的高楼是国际饭店，1934年由著名建筑师邬达克设计，建成时是上海乃至全亚洲最高的建筑，外观在当时极为现代。它的地下建有远东最大的保险库之一，比外滩银行的金库还要早。大厅地面上有一块特别的铜牌，标记着“上海大地原点”——上海所有公路里程都从这个点开始丈量。这里曾名流云集：京剧大师梅兰芳出访苏联前，在此举办盛大舞会；1936年喜剧大师卓别林访问上海，梅兰芳等名流也在饭店设宴款待。国际饭店不只是一家饭店，更是上海摩登年代的见证。大楼共24层、高83.8米，是典型的装饰艺术风格，由匈牙利籍建筑师邬达克设计，“远东第一高”的称号一直保持到上世纪80年代。大堂西饼屋天天排着长队——上海人最认这里的蝴蝶酥，酥皮叠了两百多层，奶香浓郁。买一袋蝴蝶酥、看一眼大地原点，是老上海最有仪式感的打卡方式。',
      en:'The elegant tall building to the west is the Park Hotel. It was designed by the famous architect László Hudec and opened in 1934 as the tallest building in Shanghai and in all of Asia, with a very modern look for its time. Deep underground it built one of the largest safes in the Far East, even earlier than the bank treasuries on the Bund. On the lobby floor is a special copper plate marking the “zero point of Shanghai” — the exact spot from which all road distances in the city are measured. Many famous guests came here. Peking Opera master Mei Lanfang held a grand party in the hotel before his trip to the Soviet Union. When comedy master Charlie Chaplin visited Shanghai in 1936, Mei Lanfang and other celebrities hosted a banquet for him right here. The Park Hotel is not just a hotel; it is a witness to the glamorous age of old Shanghai. The hotel has 24 floors and stands 83.8 meters tall, a classic Art Deco work by the Hungarian-Slovak architect Hudec, and it kept the title of tallest building in the Far East until the 1980s. Its bakery has a queue every day: locals come for its butterfly pastries, made with more than 200 flaky layers and rich butter flavor. A bag of pastries plus a look at the zero-point mark is the most classic Shanghai visit.'} }
  ],
  structure:[
    '<b>开场定位：</b>人民广场是上海“大地原点”与城市中心',
    '<b>历史切入：</b>跑马厅 → 1951年改建人民广场，交代空间变迁',
    '<b>建筑巡礼：</b>按方位介绍博物馆、历史博物馆、规划馆、国际饭店',
    '<b>红色点睛：</b>中共一大纪念馆与建党故事',
    '<b>收尾升华：</b>“读懂人民广场，就读懂上海”'
  ],
  vocab:[
    {zh:'人民广场',en:"People's Square"},
    {zh:'跑马厅 / 跑马总会',en:'the Race Course / the Race Club'},
    {zh:'中共一大纪念馆',en:'the Memorial of the First CPC National Congress'},
    {zh:'上海博物馆',en:'the Shanghai Museum'},
    {zh:'青铜大鼎',en:'a bronze ding vessel'},
    {zh:'城市规划展示馆',en:'the Urban Planning Exhibition Center'},
    {zh:'国际饭店',en:'the Park Hotel'},
    {zh:'邬达克',en:'László Hudec'}
  ],
  keywords:[
    {zh:'城市绿肺',en:'the green lung of the city'},
    {zh:'大地原点',en:'the zero point of the city'}
  ],
  body:[
    { v:3, zh:'各位游客，欢迎来到人民广场。这里是上海的地理中心，地面上能看到“上海公路零公里”标志，三条国道都从这里出发。广场总面积约14万平方米，人民大道横贯其中，把广场分成两半：北面自西向东是上海大剧院、人民大厦和城市规划展示馆，再往北是绿树成荫的人民公园；南面正中是大型平台和圆形音乐喷泉“浦江之光”，喷泉按上海地图轮廓设计，每小时喷射一次，非常壮观。东部是花木花坛，西部是大片草坪，上千只广场鸽是孩子们的最爱。',
      en:'Ladies and gentlemen, welcome to People’s Square, the geographic center of Shanghai. On the ground you can find the “Zero Point of Highways, Shanghai”, where three national highways begin. The square covers about 140,000 square meters. People’s Avenue runs across it and divides it into two parts. In the north stand the Shanghai Grand Theater, People’s Mansion and the Urban Planning Exhibition Center, and beyond them lies the tree-lined People’s Park. To the south is a large terrace and a round music fountain named “Light of the Huangpu River”, shaped like the map of Shanghai and playing every hour. The east is full of flowers and trees, while the west has wide lawns where over a thousand pigeons delight the children.' },
    { v:3, zh:'一百多年前，这里曾是英国人经营的跑马厅，上世纪三四十年代号称“远东第一跑马厅”；1951年改建为人民广场和人民公园，土地回到了人民手中。这里还是上海最大的交通枢纽之一，地下是地铁1、2、8号线的交汇点，旁边就是“中华商业第一街”南京路。',
      en:'Over a hundred years ago, this area was a British-run racecourse — in the 1930s and 40s, the “No. 1 Racecourse in the Far East”. In 1951 it was rebuilt into People’s Square and People’s Park, and the land returned to the people. It is also one of the city’s biggest transport hubs: underground, Metro Lines 1, 2 and 8 meet in one station, and Nanjing Road, Shanghai’s most famous shopping street, is just beside it.' },
    { v:3, zh:'正南面“天圆地方”造型的是上海博物馆，1996年开馆，馆藏文物102万余件，其中珍贵文物约14万件，青铜器、陶瓷、书画收藏享誉全国。北侧带钟楼的是上海市历史博物馆，馆舍就是1933年的原跑马总会大楼，三件镇馆之宝别错过：汇丰铜狮、百子大礼轿，还有鸦片战争中保卫上海的民族英雄陈化成的铜炮。',
      en:'To the south, the round-top, square-base building is the Shanghai Museum, opened in 1996. It holds over 1.02 million items, about 140,000 of them graded treasures, with national-famous collections of bronzes, ceramics and paintings. On the north side stands the clock-tower Shanghai History Museum, in the former Race Club of 1933. Don’t miss its three treasures: the HSBC bronze lions, the hundred-children wedding sedan, and the bronze cannon of Chen Huacheng, who defended Shanghai in the Opium War.' },
    { v:5, zh:'东侧的城市规划展示馆，屋顶像四朵盛开的白玉兰——上海市花。馆内一层“上海印象”、二层“人文之城”、三层“创新之城”、四层“生态之城”，三楼的5D数字沉浸模型宛如数字孪生上海，几分钟就能看懂城市的昨天、今天与明天。',
      en:'To the east is the Urban Planning Exhibition Center, whose roof blooms like four white magnolias, the city flower. Its four floors are themed Impressions, People City, Innovation City and Eco City. The 5D digital model on the third floor is like a living twin of Shanghai, showing the city’s past, present and future in minutes.' },
    { v:3, zh:'西侧的国际饭店1934年建成，高83.8米，曾是“远东第一高楼”，纪录保持了半个世纪；地下有过远东最大保险库，大厅铜牌就是“上海大地原点”。梅兰芳出访苏联前曾在此办舞会，喜剧大师卓别林1936年访沪时也在此受到宴请。',
      en:'To the west is the Park Hotel, completed in 1934 at 83.8 meters — once the tallest building in the Far East, holding the record for half a century. It had one of the Far East’s largest safes underground, and the copper plate in its lobby marks the zero point of Shanghai. Mei Lanfang held a grand party here before his Soviet trip, and Charlie Chaplin was guest of honor at a banquet during his 1936 visit.' },
    { v:3, zh:'从广场步行可达中共一大纪念馆：1921年7月23日，中共一大在这幢1920年的石库门里召开，中国共产党由此诞生；2021年新馆开放。一座广场，从跑马厅到博物馆，浓缩了上海的过去、现在与未来。谢谢大家！',
      en:'A short walk away is the Memorial of the First CPC National Congress: on July 23, 1921, the First Congress opened in this 1920 Shikumen house, and the CPC was born; a new hall opened in 2021. One square — from racecourse to museums — condenses Shanghai’s past, present and future. Thank you!' }
  ]
},
/* ==================== ③ 陆家嘴 ==================== */
{
  id:'lujiazui', score:10,
  name:{ zh:'陆家嘴景区', en:'Lujiazui' },
  profile:{
    status:{ zh:'中国改革开放象征 · 世界级CBD', en:'A symbol of reform and opening-up · a world-class CBD' },
    highlight:{ zh:'三高塔刷新天际线，三十年间从农田到金融城', en:'Three landmark towers reshaped the skyline — from farmland to financial city in 30 years' }
  },
  landmarks:[
    { name:{zh:'东方明珠广播电视塔',en:'the Oriental Pearl TV Tower'}, desc:{zh:'各位请看这座造型独特的高塔——东方明珠广播电视塔，1994年建成，高468米，是世界第三高的电视塔，也是上海第一批国家5A级景区之一。她的位置十分巧妙：东北是杨浦大桥，西南是南浦大桥，两座大桥像两条巨龙，明珠塔像一颗明珠，组成“二龙戏珠”的壮丽画面。塔身共有大小11个球体，宛如“大珠小珠落玉盘”，把中国诗意与现代建筑融为一体。主观光层在263米，整座上海尽收眼底；更高的球体在350米，顶部设有旋转餐厅。高速电梯从底层到观光层只需40秒，又快又稳。塔座里还藏着一座上海城市历史发展陈列馆，老马车、商号牌匾和微缩旧上海街景，把城市六千年的变迁娓娓道来；259米处设有全透明悬空观光廊，走在玻璃地板上像踏在云端，胆大的朋友一定不要错过。夜晚塔身彩灯变幻，倒映江中，是浦东最经典的夜景。',
      en:'Please look at this special tower — the Oriental Pearl TV Tower. Completed in 1994, it is 468 meters tall, the third highest TV tower in the world, and one of Shanghai’s first national 5A tourist attractions. Its position is very clever: the Yangpu Bridge lies to the northeast and the Nanpu Bridge to the southwest. The two bridges look like two dragons, and the tower like a bright pearl, forming the famous picture of “two dragons playing with a pearl”. The tower actually has 11 spheres, big and small, like “pearls, large and small, falling on a jade plate”, a perfect mix of Chinese poetry and modern design. The main sightseeing floor is at 263 meters, where all of Shanghai lies below you. The higher sphere at 350 meters holds a revolving restaurant. The fast elevator takes you from the ground to the sightseeing floor in only 40 seconds, quickly and smoothly. At the base hides the Shanghai Municipal History Museum, with old carriages, shop signs and miniature old streets telling the city’s 6,000-year story. At 259 meters there is a fully transparent sightseeing corridor; walking on its glass floor feels like stepping on clouds, so brave friends should not miss it. At night the tower glows in changing colors mirrored in the river — the most classic night view of Pudong.'} },
    { name:{zh:'金茂大厦',en:'Jin Mao Tower'}, desc:{zh:'各位请看金茂大厦，1999年落成，高420.5米，共88层，建成时是上海第一高楼。它的造型最有中国味：建筑师从中国古塔中获得灵感，楼体自下而上层层收分，像一座现代化的宝塔；“88”和处处出现的数字“8”，在中国文化里寓意发财吉祥。高速电梯只需45秒就能从底层直达88层观光厅，高度340.1米。天气晴朗时，黄浦江、外滩老建筑和浦东楼群都看得清清楚楚。它与旁边的上海环球金融中心、上海中心大厦并肩而立，组成充满未来感的天际线。金茂大厦不只是一座摩天楼，更是上海过去与未来的象征。楼里还藏着一项世界纪录：53层到87层是金茂君悦大酒店，中庭从56层一直挑高到顶楼，约152米，曾被吉尼斯认证为世界最高的酒店中庭，仰头望去如坐井观天。88层观光厅还有无遮挡的玻璃“云中步道”，直视脚下340米的街道，非常刺激。',
      en:'Please look at Jin Mao Tower. Completed in 1999, it is 420.5 meters tall with 88 floors, and it was the tallest building in Shanghai when it opened. Its design is full of Chinese style. The architects took their idea from ancient Chinese pagodas: the building tapers floor by floor as it rises, just like a modern pagoda. The number 88, and the number 8 everywhere, means good luck and wealth in Chinese culture. The super-fast elevator takes you from the ground to the observatory on the 88th floor in only 45 seconds — 340.1 meters above the city. On a clear day, you can clearly see the Huangpu River, the old buildings of the Bund and the towers of Pudong. It stands together with the Shanghai World Financial Center and Shanghai Tower, creating a futuristic skyline. Jin Mao Tower is not just a skyscraper; it is a symbol of Shanghai’s past and future. It also holds a world record. Floors 53 to 87 are the Grand Hyatt Hotel, whose atrium rises from the 56th floor to the top, about 152 meters high — once listed by Guinness as the tallest hotel atrium in the world; looking up is like watching clouds from the bottom of a well. The 88th floor also has a glass “skywalk” with no blocked view, so you can look straight down 340 meters to the streets below — truly exciting.'} },
    { name:{zh:'上海中心大厦',en:'Shanghai Tower'}, desc:{zh:'各位请看这座最宏伟的高楼——上海中心大厦，2015年建成，总高632米，是中国第一、世界第二高楼。最特别的是它的外形：楼体自下而上旋转约120度，像一条正腾空而起的巨龙。这个造型不只是好看，还能大大减小强风对大楼的冲击，更加安全、节能。它拥有世界上最快的电梯之一，约55秒即可抵达118层的观光厅——“上海之巅”。站在632米的高空，黄浦江像一条丝带，外滩、金茂大厦、环球金融中心都在脚下，天气好时视野极其震撼。三座超高塔呈三角形排列，共同托起陆家嘴的经典画面。上海中心是现代上海的象征，也是人类工程的奇迹。楼内还有两件“秘密武器”：双层玻璃幕墙像保温瓶，可节能约24%；125层附近装有一台重达1000吨的阻尼器“上海慧眼”，台风天里它会反向摆动，稳住整座大楼。84层到110层是J酒店，世界最高的酒店之一。在“上海之巅”寄一张明信片，连邮戳都带着632米的高度。',
      en:'Please look at the grandest tower of all — Shanghai Tower. Completed in 2015, it rises 632 meters, making it the tallest building in China and the second tallest in the world. Its shape is the most special feature: the whole building twists about 120 degrees as it rises, like a dragon climbing into the sky. This design is not just beautiful; it also greatly reduces the push of strong winds, making the tower safer and saving energy. It has one of the fastest elevators in the world, reaching the observation deck on the 118th floor — the “Shanghai Summit” — in about 55 seconds. At 632 meters high, the Huangpu River looks like a silk ribbon, and the Bund, Jin Mao Tower and the World Financial Center all lie at your feet. On a clear day the view is stunning. The three supertalls stand like a triangle, creating the classic picture of Lujiazui. Shanghai Tower is a symbol of modern Shanghai and a marvel of human engineering. Inside are two secret weapons. Its double-layer glass skin works like a thermos and saves about 24 percent of energy, and near the 125th floor sits the 1,000-ton damper “Shanghai Eye”, which swings the other way during typhoons to steady the building. Floors 84 to 110 hold the J Hotel, one of the highest hotels in the world. You can even send a postcard from the summit, with a postmark from 632 meters above the ground.'} }
  ],
  structure:[
    '<b>开场震撼：</b>浦西望浦东，用高度数字先声夺人',
    '<b>历史对比：</b>1990年浦东开发开放，从“烂泥渡路”到金融城',
    '<b>三塔递进：</b>按建成年代讲东方明珠→金茂→上海中心',
    '<b>文化穿插：</b>建筑造型中的中国意象（玉盘、古塔、祥云）',
    '<b>收尾立意：</b>三栋楼是中国速度与高度的缩影'
  ],
  vocab:[
    {zh:'陆家嘴',en:'Lujiazui'},{zh:'东方明珠广播电视塔',en:'the Oriental Pearl TV Tower'},
    {zh:'金茂大厦',en:'Jin Mao Tower'},{zh:'上海中心大厦',en:'Shanghai Tower'},
    {zh:'摩天大楼',en:'skyscraper'},{zh:'观光厅',en:'observation deck'},
    {zh:'浦东开发开放',en:"Pudong's development and opening-up"},
    {zh:'金融中心',en:'financial center'},{zh:'旋转餐厅',en:'revolving restaurant'}
  ],
  keywords:[
    {zh:'大珠小珠落玉盘',en:'pearls, large and small, falling on a jade plate'},
    {zh:'垂直城市',en:'a vertical city'}
  ],
  body:[
    { v:3, zh:'各位游客，欢迎来到陆家嘴。这里与外滩仅一江之隔，却是中国最具活力的金融贸易区和世界级城市天际线。上海被称为“中国摩天楼之都”，而陆家嘴就是最好的橱窗。',
      en:'Ladies and gentlemen, welcome to Lujiazui. Just across the river from the Bund, this is China’s most dynamic financial and trade zone and home to a world-class skyline. Shanghai is called the capital of skyscrapers in China, and Lujiazui is its best showcase.' },
    { v:3, zh:'先说说“浦东”：“浦”指黄浦江，“东”就是江之东。上世纪80年代，这里还只有农田、仓库和码头，民间流传“宁要浦西一张床，不要浦东一间房”。1990年4月18日，中央宣布开发开放浦东；1993年浦东新区管委会成立。如今浦东面积1210平方公里、人口578万，是上海16个区中面积第二、人口最多的区。三十多年，滩涂变金融城，这就是浦东奇迹。',
      en:'First, the name “Pudong”: “pu” means the Huangpu River and “dong” means east. In the 1980s there was little here but farmland, warehouses and wharves, and locals said “a bed in Puxi is better than a flat in Pudong”. On April 18, 1990, the state announced the development and opening-up of Pudong, and the district administration was set up in 1993. Today Pudong covers 1,210 square kilometers with 5.78 million people — the second largest and most populous of Shanghai’s 16 districts. In just 30 years, muddy flats became a financial city. That is the Pudong miracle.' },
    { v:3, zh:'第一座地标是东方明珠广播电视塔，1994年建成，高468米，世界第三高电视塔。11个球体大小错落，创意来自唐诗“大珠小珠落玉盘”；北望杨浦大桥、南邻南浦大桥，恰似“二龙戏珠”。主观光层在263米，350米球体有旋转餐厅，电梯40秒直达。',
      en:'The first landmark is the Oriental Pearl TV Tower, completed in 1994 at 468 meters — the third tallest TV tower in the world. Its 11 spheres recall the poem line “pearls, large and small, falling on a jade plate”. With the Yangpu Bridge to the northeast and the Nanpu Bridge to the southwest, it looks like “two dragons playing with a pearl”. The main deck is at 263 meters, a revolving restaurant sits in the 350-meter sphere, and the elevator takes only 40 seconds.' },
    { v:3, zh:'旁边的金茂大厦1999年落成，高420.5米、88层，以中国古塔为灵感，处处暗含吉祥数字“8”，电梯45秒直达340.1米高的88层观光厅。最高的是上海中心大厦，2015年建成，高632米，中国第一、世界第二；楼体旋转120度如腾龙升空，可御风节能，55秒即可登上118层“上海之巅”。',
      en:'Next stands Jin Mao Tower of 1999 — 420.5 meters and 88 floors, inspired by ancient pagodas and full of the lucky number 8; its elevator reaches the 88th-floor observatory at 340.1 meters in 45 seconds. The tallest is Shanghai Tower, completed in 2015 at 632 meters — China’s tallest and the world’s second. It twists 120 degrees like a rising dragon, a form that resists wind and saves energy, and in 55 seconds you reach the 118th-floor “Shanghai Summit”.' },
    { v:5, zh:'金茂旁边是上海环球金融中心，顶部梯形开孔像一个“瓶起子”。它与金茂、上海中心组成游客口中的“厨房三件套”，是上海最经典的拍照机位。',
      en:'Beside Jin Mao is the Shanghai World Financial Center, whose trapezoidal opening earns it the nickname “the bottle opener”. Together with Jin Mao and Shanghai Tower it forms the “kitchen set”, Shanghai’s most photographed skyline.' },
    { v:3, zh:'陆家嘴还有两家国家5A级景区：除了东方明珠，还有上海科技馆；上海海洋水族馆和大自然野生昆虫馆则是孩子们的最爱。傍晚可以沿滨江大道漫步，一边是新时代的未来建筑，一边是外滩的历史轮廓——难怪人们说，没到陆家嘴，不算到过上海。谢谢大家！',
      en:'Lujiazui also has two national 5A attractions: besides the Oriental Pearl, there is the Shanghai Science and Technology Museum, while the Ocean Aquarium and the Wild Insect Kingdom are children’s favorites. In the evening, walk along the Riverside Promenade — futuristic buildings on one side, the historic outline of the Bund on the other. No wonder people say a trip to Shanghai is never complete without Lujiazui. Thank you!' }
  ]
},
/* ==================== ④ 豫园 ==================== */
{
  id:'yuyuan', score:10,
  name:{ zh:'豫园景区', en:'Yu Garden' },
  profile:{
    status:{ zh:'江南古典园林杰出代表 · 海上名园', en:'An outstanding classical Jiangnan garden · the famous garden of Shanghai' },
    highlight:{ zh:'明代私人花园，“奇秀甲于东南”', en:'A Ming-dynasty private garden praised as “the finest under the southeast”' }
  },
  landmarks:[
    { name:{zh:'三穗堂和大假山',en:'Sansui Hall and the Grand Rockery'}, desc:{zh:'各位请看这座气宇轩昂的大厅——三穗堂，清代乾隆年间（1760年）建成，是进入豫园的主要建筑。堂名来自“禾生三穗”的古老典故，一茎禾苗长出三穗，象征五谷丰登、身体健康、事业有成；旧时这里用于官员议事和举行庆典。请看木门上的雕刻，稻麦、瓜果、花卉，样样栩栩如生，正好呼应堂名。走出堂后，是欣赏镇园之宝大假山的最佳位置：大假山高约12米，用约2000吨武康黄石叠成，出自明代叠山名家张南阳之手，是江南现存最大、最精美的明代黄石假山，磴道盘旋，登顶可俯瞰全园。请抬头看堂内匾额，正中“三穗堂”，对面还有“城市山林”四字，称赞这座园林是闹市中的一片山林。清代这里是地方官员宣讲圣谕、宴请宾客的地方，所以厅堂格外高大敞亮，廊下门窗的木雕也最见工匠心思。',
      en:'Please look at this grand hall — Sansui Hall, the Hall of Three Ears of Grain. Built in 1760 during the Qing Dynasty, it is the main entrance of Yu Garden. Its name comes from an old story: a single stalk bearing three ears of grain, which stands for a good harvest, good health and success in career. In old times it was used for official meetings and celebrations. Please look at the wooden doors: the carvings of rice, wheat, fruits and flowers are lively and true to life, matching the hall’s name. Behind the hall is the best spot to view the garden’s treasure, the Grand Rockery. About 12 meters high and made of some 2,000 tons of yellow Wukang stone, it was created by the Ming master Zhang Nanyang. It is the largest and finest surviving Ming yellow-stone rockery in Jiangnan, with winding steps leading to a top view of the whole garden. Please look up at the plaques overhead: the hall’s own name faces four characters meaning “mountains and forests inside the city”, praising this garden as a piece of nature in the busy town. In the Qing Dynasty, local officials gave public teachings and held banquets here, so the hall is unusually tall and bright, and the fine wooden carvings on its doors show the craftsmen’s best skill.'} },
    { name:{zh:'玉玲珑和玉华堂',en:'the Jade Exquisite Rock and Yuhua Hall'}, desc:{zh:'各位请看豫园的头号宝贝——玉玲珑。它不是普通的石头，而是一块太湖石。好的太湖石讲究“瘦、皱、漏、透”，玉玲珑正是完美典范：身形修长，周身布满大大小小的孔洞。最神奇的是“一炉香、一壶水”：在石底点一炉香，青烟会从每个孔里袅袅升起；在石顶倒一壶水，水流会从每个孔中汩汩流出，就像变魔术。它高约3米，有72个孔，是江南三大名石之一。灵石旁的玉华堂，曾是园主潘允端的书房；“玉”象征君子纯洁高尚的品格，在这里能体会中国文人读书、赏石、亲近自然的生活雅趣。关于它的来历还有个故事：相传它本是北宋徽宗“花石纲”的贡石，运送途中船沉石失，后来流落到上海三林塘，明代被潘家购得；为把灵石运入园中，潘家还专门修了玉玲珑阁。园主潘允端在玉华堂读书赏石四十余年，把这块石头视作最知心的朋友。',
      en:'Please look at Yu Garden’s greatest treasure — the Jade Exquisite. It is no ordinary stone but a Taihu stone. A fine Taihu stone should be slender, wrinkled, hollowed and pierced, and this rock is the perfect example: tall and thin, covered with holes big and small. Its magic is best seen with incense and water. Light incense beneath it, and soft smoke rises from every hole; pour a pot of water on top, and water flows out of every hole like magic. About 3 meters tall with 72 holes, it is one of the three famous rocks of Jiangnan. Beside it stands Yuhua Hall, once the study of Pan Yunduan, the owner of the garden. Jade stands for the pure and noble character of a Chinese gentleman, and here you can feel the elegant life of old scholars — reading, enjoying stones and staying close to nature. There is also a story about its past. It is said to have been a tribute stone for Emperor Huizong of the Northern Song; the boat sank on the way, the stone was lost and later found near Shanghai, and the Pan family bought it in the Ming Dynasty. They even built a special hall to bring it into the garden. Pan Yunduan studied and enjoyed this stone for over 40 years and treated it as his closest friend.'} },
    { name:{zh:'梅妻鹤子和铁狮',en:'“Plum Wife & Crane Sons” and the Iron Lions'}, desc:{zh:'请看窗格里这组泥塑——“梅妻鹤子”，出自清代，距今约三百年。它讲的是北宋名士林逋的故事：他隐居杭州孤山，终身不仕不娶，只爱种梅养鹤，人们说他“以梅为妻、以鹤为子”，形容他清雅脱俗。再请看旁边这对铁狮，已有700多年历史，铸于元代。它们经历过不平凡的旅程：抗战时期被劫往日本东京，1945年抗战胜利后回到中国，上世纪50年代豫园整修时安放于此。在中国文化里，狮子象征权力与尊严：雌狮脚抚幼狮，寓意子孙满堂；雄狮脚踩绣球，寓意权力在握。它们一左一右，守护豫园至今。林逋最爱梅花，写下“疏影横斜水清浅，暗香浮动月黄昏”的千古名句；您看窗格里白鹤展翅、梅枝横斜，正是诗中的意境。游廊里这样的泥塑还有好几组，都是三百年前工匠用普通泥土捏出的故事，建议大家放慢脚步，一幅一幅地看。',
      en:'Please look at the clay sculpture in the window frame — “Plum Wife and Crane Sons”, made in the Qing Dynasty about 300 years ago. It tells the story of Lin Bu, a Northern Song scholar. He lived alone as a hermit by West Lake in Hangzhou, never taking an official post or a wife. He only loved planting plum trees and raising cranes, so people said he treated the plum tree as his wife and the crane as his sons — a picture of a pure, free spirit. Now look at the pair of iron lions beside it. Over 700 years old, they were cast in the Yuan Dynasty. They had an unusual journey: taken to Tokyo during the war, they returned to China in 1945 and were placed here in the 1950s. In Chinese culture, lions stand for power and dignity: the female plays with a baby lion for a big family, while the male rests a paw on a ball for authority. Together they guard Yu Garden to this day. Lin Bu loved plum blossoms most and wrote the famous lines: “Sparse shadows slant over shallow clear water; faint fragrance floats in the moonlit evening.” Here a crane spreads its wings and plum branches lean across, just like the world in his poem. There are several more clay scenes along this corridor, all shaped from ordinary clay by craftsmen 300 years ago, so please slow down and enjoy them one by one.'} },
    { name:{zh:'鱼乐榭',en:'Yule Xie (the Fish Joy Pavilion)'}, desc:{zh:'这座临水的小巧建筑是鱼乐榭，名字来自一个有趣的哲学故事。战国思想家庄子和朋友在水边看鱼，庄子说：“你看，鱼儿游得多快乐啊！”朋友反问：“你又不是鱼，怎么知道鱼很快乐？”庄子答道：“你又不是我，怎么知道我不知道鱼的快乐呢？”所以这里自古就是观鱼、思考自由与快乐的地方。请大家再看榭旁这堵隔水花墙：溪水被墙一分为二，却没有被挡住，反而从墙下流过，看起来比实际更长、更深，仿佛没有尽头。这是中国园林“小中见大”的经典手法——小小空间，也能做出幽深山水。水边这株老紫藤也有上百年，春天紫花垂满花架，是豫园最安静的角落；小溪尽头还有一座半亭，亭、榭、花墙围成一方小天地。中国文人相信，观鱼可知鱼乐，鱼乐即我乐，大家不妨在此坐一坐，体会这份自在。',
      en:'This small waterside building is Yule Xie, the Fish Joy Pavilion. Its name comes from an old philosophical story. The thinker Zhuangzi watched fish with a friend and said, “Look how happy the fish are!” His friend asked, “You are not a fish — how can you know the fish are happy?” Zhuangzi answered, “You are not me — how can you know I don’t know?” So this has long been a place to watch fish and think about freedom and joy. Please also look at the low wall across the stream. It divides the water but does not stop it; the stream flows beneath the wall and looks longer and deeper than it really is, as if it had no end. This is the classic Chinese garden trick of “seeing the grand within the small”: even a tiny space can hold deep mountains and waters. The old wisteria by the water is also over a hundred years old; in spring its purple flowers hang all over the frame, making this the quietest corner of the garden, and a small half-pavilion stands at the end of the stream. Chinese scholars believed that watching happy fish made the watcher happy too, so please sit here for a moment and feel that freedom.'} },
    { name:{zh:'万花楼和穿云龙',en:'Wanhua Hall and the Cloud-Piercing Dragon Wall'}, desc:{zh:'园中有两处特别景致：穿云龙墙与万花楼。请看院墙上的巨龙，龙头昂扬，龙身嵌在墙中，仿佛正腾云驾雾、飞向天空，所以叫“穿云龙”。在中国文化里，龙是吉祥与权力的象征，这条龙也是豫园群龙中最生动的一条。再看这座秀美的万花楼，“万花”就是万朵鲜花的意思。旧时这里是女眷赏花休憩的地方，温婉雅致。请留意楼周的窗户：每一扇漏窗形状都不一样，透过圆窗、六角窗、花形窗望出去，外面的竹石花木自成一幅小画，像一张张明信片。一龙一楼，一个雄壮、一个柔美，正好展现豫园的两种魅力。请看楼前这棵高大的古银杏，已有四百多岁，建楼时工匠特意把它保留下来，让小楼“长”在古树旁，秋天满树金黄。楼下原是供奉花神的花神祠，所以周围四季花木不断。这片区域不大，却把龙墙、古树、漏窗、溪流都收在一处，是豫园里最适合慢慢拍照的地方。',
      en:'There are two special spots here: the Cloud-Piercing Dragon Wall and Wanhua Hall. Please look at the dragon on the courtyard wall. Its head is raised high and its body runs through the wall, as if it were flying into the clouds — hence its name, the Cloud-Piercing Dragon. In Chinese culture the dragon means good luck and power, and this is the most vivid of Yu Garden’s dragon walls. Now look at the beautiful Wanhua Hall; its name means “ten thousand flowers”. In old times it was a place for the ladies of the family to rest and enjoy the garden. Notice the windows around it: every lattice window has a different shape — round, six-sided or flower-shaped — and through each one the bamboo, stones and flowers outside form a small picture, like a postcard. One dragon and one hall, one strong and one gentle — together they show the two charms of Yu Garden. Please look at the tall old ginkgo tree in front of the hall. It is over 400 years old; when the hall was built, the craftsmen kept it on purpose, letting the building “grow” beside the ancient tree, which turns golden in autumn. The lower floor was originally a shrine to the Flower Spirit, so flowers and trees bloom here all year round. This small area gathers a dragon wall, an old tree, lattice windows and a stream in one place — the best spot in the garden for slow photos.'} }
  ],
  structure:[
    '<b>开场定位：</b>豫园位置、始建年代（明嘉靖）、园主潘允端与“豫悦老亲”',
    '<b>游线推进：</b>三穗堂 → 大假山 → 铁狮 → 鱼乐榭 → 万花楼 → 玉玲珑',
    '<b>文化典故：</b>林逋梅妻鹤子、庄子濠梁之辩、花石纲传说',
    '<b>园林审美：</b>讲透太湖石“皱漏瘦透”四字',
    '<b>收尾：</b>小中见大，都市中的江南诗意'
  ],
  vocab:[
    {zh:'豫园',en:'Yu Garden'},{zh:'江南古典园林',en:'a classical Jiangnan garden'},
    {zh:'三穗堂',en:'Sansui Hall'},{zh:'大假山',en:'the Grand Rockery'},
    {zh:'鱼乐榭',en:'the Fish Joy Pavilion (Yule Xie)'},
    {zh:'万花楼',en:'Wanhua Hall'},{zh:'玉玲珑',en:'the Jade Exquisite Rock'},
    {zh:'玉华堂',en:'Yuhua Hall'},{zh:'太湖石',en:'Taihu stone'},
    {zh:'皱、漏、瘦、透',en:'wrinkled, hollowed, slender and pierced'},
    {zh:'花石纲',en:"the Flower-Stone Convoy of Emperor Huizong"}
  ],
  keywords:[
    {zh:'豫悦老亲',en:'to bring joy and peace to one’s parents'},
    {zh:'小中见大',en:'seeing the grand within the small'}
  ],
  body:[
    { v:3, zh:'各位游客，欢迎来到豫园景区。这里位于外滩以南的老城厢，曾是上海最早的城市中心，被称为“老上海的根”。南面的城隍庙最初为纪念一位古代将军而建，明代起供奉上海城隍，历经修缮，1994年重新开放，至今保留传统格局。',
      en:'Ladies and gentlemen, welcome to Yu Garden. This area lies south of the Bund in the Old Town, once the earliest city center of Shanghai, often called the root of the city. To the south stands the City God Temple. It was first built for an ancient general and later honored Shanghai’s city god in the Ming Dynasty. After many repairs, it reopened in 1994 and still keeps its traditional layout.' },
    { v:3, zh:'西北面就是豫园，上海最大、最著名的古典园林。它始建于1559年，由明代官员潘允端为父亲所建，“豫”是“愉悦双亲”的意思。全园分水、建筑、花木、假山四大要素，现分六大景区、40多个景点。园南是荷花池和九曲桥——“九”在中国文化里是吉祥之数；池心的湖心亭建于1784年，1855年改为茶楼，是上海最古老、最有名的茶楼之一。',
      en:'To the northwest is Yu Garden, Shanghai’s largest and most famous classical garden. It was first built in 1559 by the Ming official Pan Yunduan for his father; “yu” means pleasing one’s parents. It brings together the four key features of a Chinese garden — water, buildings, plants and rocks — in six sections with over 40 scenic spots. South of the garden lies a lotus pond with the Nine-Turning Bridge, and nine is a lucky number in Chinese culture. The Mid-Lake Pavilion in the pond was built in 1784 and became a teahouse in 1855 — one of the oldest and best-known teahouses in Shanghai.' },
    { v:3, zh:'我们首先来到三穗堂，建于清代乾隆年间，堂名寓意五谷丰登，门上稻麦瓜果的雕刻正与堂名呼应。堂后是镇园之宝大假山：高约12米，用2000吨武康黄石叠成，出自明代叠山名家张南阳之手，是江南现存最大的明代黄石假山。',
      en:'We first enter Sansui Hall of the Qing Dynasty. Its name wishes for a rich harvest, and the carvings of rice, wheat and fruits on the doors match that wish. Behind it stands the treasure of the garden, the Grand Rockery: about 12 meters high and made of 2,000 tons of yellow Wukang stone by the Ming master Zhang Nanyang — the largest surviving Ming yellow-stone rockery in Jiangnan.' },
    { v:5, zh:'游廊旁的“梅妻鹤子”泥塑，讲北宋林逋隐居孤山、种梅养鹤的故事；旁边一对元代铁狮已有700多岁，抗战时被劫往东京，1945年归来，至今守护豫园。临水的鱼乐榭出自庄子“子非鱼，安知鱼之乐”的辩论；隔水花墙让小溪显得无穷无尽，是“小中见大”的妙笔。万花楼的漏窗形状各异，穿云龙墙栩栩如生。',
      en:'By the corridor, the “Plum Wife and Crane Sons” sculpture recalls the hermit Lin Bu, while a pair of 700-year-old Yuan iron lions — taken to Tokyo in the war and returned in 1945 — still guard the garden. The waterside Fish Joy Pavilion comes from Zhuangzi’s debate over fish happiness, and its low wall makes the stream seem endless. Wanhua Hall’s lattice windows are all different, and the Cloud-Piercing Dragon Wall is vividly alive.' },
    { v:3, zh:'请看这块灵石——玉玲珑，江南三大名石之一，高约3米、72孔，具“皱、漏、瘦、透”之美：石底燃香，孔孔冒烟；石顶浇水，孔孔流泉，相传是北宋“花石纲”遗物。',
      en:'Please look at the Jade Exquisite, one of Jiangnan’s three famous Taihu stones — 3 meters tall with 72 holes, wrinkled, hollowed, slender and pierced. Smoke rises from every hole with incense below, and water trickles from every hole when poured on top. It is said to survive from the Northern Song Flower-Stone Convoy.' },
    { v:3, zh:'园外的集市有上百家店铺餐馆，上海老街展现着600年的建筑变迁，是买纪念品的好地方；2014年一次国际会议期间，各国元首夫人们曾在此品尝小吃、观看民俗表演。从现代街头跨过九曲桥，你就走进了老上海。谢谢大家！',
      en:'Around the garden, a lively market holds over 100 shops and restaurants, and Shanghai Old Street shows 600 years of architectural change — a wonderful place for souvenirs. During an international meeting in 2014, the first ladies of many countries tasted local snacks and watched folk performances here. Cross the Nine-Turning Bridge from the modern street, and you step into old Shanghai. Thank you!' }
  ]
},
/* ==================== ⑤ 玉佛寺 ==================== */
{
  id:'jadebuddha', score:10,
  name:{ zh:'玉佛寺景区', en:'the Jade Buddha Temple' },
  profile:{
    status:{ zh:'沪上名刹 · 江南禅宗寺院', en:'A famous Shanghai monastery · a Jiangnan Chan Buddhist temple' },
    highlight:{ zh:'两尊缅甸白玉佛像为镇寺之宝', en:'Two white-jade Buddhas from Myanmar are the temple’s treasures' }
  },
  landmarks:[
    { name:{zh:'天王殿',en:'the Hall of Heavenly Kings'}, desc:{zh:'各位游客，我们面前是天王殿，进入玉佛寺的第一重殿。正中这位胖胖的、笑口常开的佛是弥勒佛，代表光明欢喜的未来佛，他在用笑容欢迎每一位来客。弥勒佛背后、面朝大雄宝殿的是韦驮菩萨，他是寺院的护法神，手持金刚杵，日夜守护佛法与寺院。请看左右两侧，是威风凛凛的四大天王，各护一方：持琵琶的调弦，带来和谐太平；持宝剑的护持佛法；手持雨伞的遮风挡雨、护佑世界远离邪恶；手缠灵蛇的体察民情、倾听百姓心愿。他们合起来正好寄托“风调雨顺、国泰民安”的美好愿望。请看弥勒两旁的对联：“大肚能容，容天下难容之事；开口便笑，笑世间可笑之人”，道尽中国人的处世智慧。这位笑佛是未来佛弥勒的中国式化身——布袋和尚，相传他常背布袋、笑口常开地走在民间。进门先学他笑一笑，再带着欢喜心开始参观。',
      en:'Ladies and gentlemen, before us is the Hall of Heavenly Kings, the first hall of the Jade Buddha Temple. In the center sits the fat, happy Maitreya, the Future Buddha, welcoming every visitor with his big smile. Behind him, facing the Grand Hall, stands Skanda, the guardian of the monastery. Holding his weapon, he protects the temple and the Buddha’s teachings day and night. On the left and right stand the Four Heavenly Kings, each protecting one direction. The one with a lute tunes its strings and brings peace and harmony; the one with a sword protects the Buddhist teachings; the one with an umbrella shields the world from evil; and the one holding a divine snake listens to the wishes of all people. Together they carry the beautiful Chinese wish for favorable weather, a peaceful country and a happy people. Please read the couplet beside Maitreya: “A big belly can bear all that the world cannot bear; an open mouth laughs at all the laughable people.” It carries Chinese wisdom for life. This laughing Buddha is the Chinese form of Maitreya — the monk Budai, who walked among the people with a cloth bag and a big smile. Learn his smile at the door, and begin the tour with a happy heart.'} },
    { name:{zh:'大雄宝殿',en:'the Grand Hall (Daxiong Baodian)'}, desc:{zh:'沿中轴线向前，我们来到全寺最重要的大雄宝殿。一进门就能看到三尊大佛：正中是释迦牟尼佛，右手结印，仿佛正在讲经说法；他左侧是阿弥陀佛，右侧是药师佛，这就是汉传佛教常说的“横三世佛”。请大家细看佛面：安详、慈悲又充满智慧，让人心生宁静。大殿两侧分列十八罗汉，每一尊表情、姿势各不相同，有的笑、有的思、有的怒，他们的职责是护持佛法。再请大家转到殿后，整面墙壁是一幅巨大的海岛观音彩塑：观音立于海浪仙山之间，人物众多、细节精妙，是寺中不可错过的艺术精品。这幅“海岛观音”讲述的是善财童子五十三参的故事：他先后向53位老师求法，最后在观音身边悟道，整座雕塑有上百个人物，海浪、仙山、童子、龙女层次分明。三尊大佛高4.6米，面容却柔和亲切，仰看时让人自然生出恭敬心。',
      en:'Walking along the central axis, we arrive at the Grand Hall, the most important hall of the temple. As you enter, you see three grand Buddhas. In the middle is Sakyamuni, his hand in a teaching gesture as if giving a sermon. On his left is Amitabha Buddha and on his right the Medicine Buddha — the classic “three Buddhas” of Chinese Buddhism. Look closely at their faces: peaceful, kind and wise, they calm the heart. On both sides stand the Eighteen Arhats, each with a different expression and pose — some smiling, some thinking, some stern — and their duty is to protect the Buddhist law. Please walk to the back of the hall. The whole wall is a huge colorful carving of Guanyin on an island in the sea, standing among waves and sacred mountains, with many figures and wonderful details — a true artistic treasure of the temple. It tells the story of the boy Sudhana’s 53 visits: he learned from 53 teachers and finally gained wisdom beside Guanyin. The carving holds over a hundred figures — waves, sacred mountains, the boy and the dragon girl — all in clear layers. The three grand Buddhas are 4.6 meters tall, yet their faces are gentle and kind, filling visitors with respect.'} },
    { name:{zh:'坐佛玉像',en:'the Seated Jade Buddha'}, desc:{zh:'现在我们来到玉佛楼，这里供奉着镇寺之宝——坐佛玉像。说起这尊玉佛，不能忘记一位中国高僧：19世纪末，普陀山的慧根法师远赴缅甸朝圣，得到当地华侨捐款和藏族工匠相助，雕成五尊玉佛；1882年归国途经上海时留下两尊，一座寺院于1900年建成，慧根成为首任住持。眼前这尊坐佛高1.95米，由一整块白玉精雕而成，玉质温润晶莹，身上还镶嵌玛瑙、翡翠等宝石。释迦牟尼结跏趺坐，面容慈悲安详，目光低垂，仿佛在为众生祈福，让瞻仰者内心顿时平静下来。今天的寺院是1918年由可成法师主持重建、历时十年而成，坐佛也在战乱中被完好保护下来。佛像重约1吨，佛身贴有金饰、镶嵌宝石，袈裟纹路极见刀工。玉佛楼内不许拍照、不许大声说话，大家可以静静瞻仰片刻，把这份安详留在心里。',
      en:'Now we come to the Jade Buddha Chamber, home to the temple’s greatest treasure — the Seated Jade Buddha. Its story begins with a Chinese monk. In the late 19th century, Master Huigen from Mount Putuo went on a pilgrimage to Myanmar. With donations from overseas Chinese and the help of local craftsmen, he had five jade Buddhas carved. Passing through Shanghai in 1882, he left two of them here. A temple was completed in 1900, and Huigen became its first abbot. The seated Buddha before us is 1.95 meters tall and was carved from a single block of white jade, warm, clear and shining, inlaid with agate, emerald and other gems. Sakyamuni sits in the lotus position, his face kind and peaceful and his eyes gently lowered, as if blessing all people. Standing before him, visitors feel their hearts grow quiet at once. The temple we see today was rebuilt from 1918 under Master Kecheng and took ten years, and the seated Buddha was kept safe through the wars. The statue weighs about one ton, with gold decoration and jewels, and the folds of its robe show marvelous carving. No photos or loud talking are allowed in this chamber, so please take a moment to look quietly and keep its peace in your heart.'} },
    { name:{zh:'卧佛玉像',en:'the Reclining Jade Buddha'}, desc:{zh:'寺中另一尊珍宝是这尊卧佛玉像，它与坐佛同为慧根法师当年从缅甸请回，也由一整块白玉雕成。佛像表现的是释迦牟尼涅槃时的情景：他向右侧身而卧，右手托着头，左脚叠于右脚之上，这一姿势在佛教里叫“涅槃像”。与坐佛相比，卧佛尺寸略小，却同样精美：衣纹流畅，玉色纯净。请看他的面部，嘴角微含笑意，神情安详自在，仿佛不是离开世界，而只是沉沉入睡，让人看了也觉得宁静、解脱。正是这两尊晶莹的玉佛，让玉佛寺在上海一百多座寺院中独树一帜，在佛教界闻名海内外。这尊小卧佛身长约1米，玉质白润，衣纹像被风吹起一样轻薄，适合近观。1989年，真禅法师又从缅甸请回一尊长约4米的大卧佛，与古玉佛相伴供奉。“涅槃”不是死亡，而是断除烦恼、得到彻底解脱，所以佛的脸上才会如此安详。',
      en:'The other treasure of the temple is this Reclining Jade Buddha, brought back from Myanmar by Master Huigen together with the seated one, and also carved from a single block of white jade. It shows Sakyamuni at the moment of Nirvana. He lies on his right side, his head resting on his right hand and one foot placed over the other — the classic “Nirvana posture” in Buddhism. A little smaller than the seated Buddha, it is just as fine, with flowing robe lines and pure, clear jade. Look at his face: a gentle smile at the corner of the mouth, serene and free, as if he were not leaving the world but simply falling into a deep sleep. Viewers feel calm and released. It is these two glittering jade Buddhas that make the temple stand out among Shanghai’s more than a hundred Buddhist monasteries, famous both in China and abroad. This small reclining Buddha is about one meter long, perfect for a close look: its jade is white and soft, and its robe folds seem as light as if blown by wind. In 1989, Master Zhenchan brought another reclining Buddha from Myanmar, about four meters long, now enshrined beside the ancient jade one. Nirvana is not death; it means the end of all troubles and complete freedom, which is why the Buddha’s face is so peaceful.'} }
  ],
  structure:[
    '<b>开场溯源：</b>慧根法师请佛、1882年建寺、1918年迁建现址',
    '<b>布局讲解：</b>按中轴线天王殿→大雄宝殿→玉佛楼',
    '<b>信仰科普：</b>简要介绍弥勒、韦驮、四大天王、十八罗汉',
    '<b>镇寺之宝：</b>详讲坐佛与卧佛的玉质、尺寸、姿态',
    '<b>礼仪提醒+收尾：</b>提醒参观礼仪，欢迎来宾'
  ],
  vocab:[
    {zh:'玉佛寺',en:'the Jade Buddha Temple'},{zh:'禅宗',en:'Chan (Zen) Buddhism'},
    {zh:'天王殿',en:'the Hall of Heavenly Kings'},{zh:'大雄宝殿',en:'the Grand Hall'},
    {zh:'弥勒佛',en:'Maitreya Buddha'},{zh:'韦驮',en:'Skanda (Wei Tuo)'},
    {zh:'四大天王',en:'the Four Heavenly Kings'},{zh:'十八罗汉',en:'the Eighteen Arhats'},
    {zh:'释迦牟尼',en:'Sakyamuni'},{zh:'涅槃',en:'Nirvana'},
    {zh:'结跏趺坐',en:'the lotus position'}
  ],
  keywords:[
    {zh:'白玉',en:'white jade'},{zh:'镇寺之宝',en:'the temple’s greatest treasure'}
  ],
  body:[
    { v:3, zh:'各位游客，欢迎来到玉佛禅寺。它位于上海市中心西北部，是上海101座佛教寺院中最著名的一座，属禅宗。虽身处繁华闹市，却保留着江南寺院的清净庄严。',
      en:'Ladies and gentlemen, welcome to the Jade Buddha Temple, in the northwest of the city center. It is the most famous of Shanghai’s 101 Buddhist monasteries and belongs to Chan Buddhism. Set in the busy city, it still keeps the pure solemnity of a Jiangnan temple.' },
    { v:3, zh:'寺院的历史与两尊玉佛紧紧相连。19世纪末，普陀山高僧慧根法师远赴缅甸朝圣，得到当地华侨捐助，又请来藏族工匠参与，雕成五尊玉佛。1882年他归国途经上海，留下坐佛、卧佛两尊；1900年寺院建成，慧根任首任住持。后来寺院毁于战火，1918年在安远路现址重建，1928年重新开放。建筑按南北中轴线布局，天王殿、大雄宝殿依次排开，两侧配殿供奉两尊玉佛。',
      en:'Its story is bound to two jade Buddhas. In the late 19th century, the monk Huigen from Mount Putuo made a pilgrimage to Myanmar, where overseas Chinese donated money and craftsmen helped carve five jade Buddhas. Passing through Shanghai in 1882, he left two — one seated, one reclining. A temple was completed in 1900 and Huigen became its first abbot. Later destroyed in war, it was rebuilt at this site on Anyuan Road in 1918 and reopened in 1928. Its main halls line a north-south axis, with the two jade Buddhas in the side halls.' },
    { v:3, zh:'第一重是天王殿。正中笑口常开的是弥勒佛，背后是护法韦驮；两侧四大天王手持琵琶、宝剑、雨伞和灵蛇，合起来正是“风调雨顺”，护佑四方。',
      en:'The first hall is the Hall of Heavenly Kings. The smiling Maitreya sits in the center with the guardian Skanda behind him. The Four Heavenly Kings on both sides hold a lute, a sword, an umbrella and a divine snake — together they stand for favorable weather and peace.' },
    { v:3, zh:'沿中轴线向前是大雄宝殿，全寺主殿。正中供奉4.6米高的鎏金释迦牟尼佛，左右为阿弥陀佛与药师佛，两侧十八罗汉神态各异；殿后还有一整壁海岛观音彩塑，值得细看。',
      en:'Along the axis stands the Grand Hall, the temple’s main hall. A 4.6-meter gilded Sakyamuni sits in the center, with Amitabha and the Medicine Buddha on each side and the Eighteen Arhats along the walls. Behind the hall is a large colorful carving of Guanyin on a sea island, well worth a close look.' },
    { v:3, zh:'现在来到玉佛楼，镇寺之宝就在这里。坐佛玉像高1.95米，由一整块白玉雕成，玉质晶莹，身上镶嵌玛瑙、翡翠，结跏趺坐，神情慈悲安详。另一尊卧佛玉像同样为整块白玉，表现释迦牟尼涅槃：侧身而卧、右手托腮，安详如入睡。晶莹玉佛让玉佛寺在佛教界独树一帜。',
      en:'Now we reach the Jade Buddha Chamber and its greatest treasure. The Seated Jade Buddha is 1.95 meters tall, carved from one block of white jade inlaid with agate and emerald, sitting in the lotus position with a kind, serene face. The Reclining Jade Buddha is also one single piece of white jade, showing Sakyamuni entering Nirvana — lying on his side, head on his hand, peaceful as if asleep. These glittering Buddhas make the temple unique in the Buddhist world.' },
    { v:3, zh:'参观时请保持安静，不录像、不大声喧哗。愿这方闹市净土给各位带来平安喜乐。我的讲解到此结束，谢谢大家！',
      en:'Please keep quiet during the visit, without filming or loud talk. May this quiet sanctuary in the busy city bring you peace and joy. That concludes my commentary. Thank you!' }
  ]
}
];
